[package]
name = "lyremill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
tilemap = { package = "bevy_simple_tilemap", version = "0.12.0" }
rand = "0.8.5"
